version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: banoohoseini
      POSTGRES_PASSWORD: 721851
      POSTGRES_DB: beautysalon_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: